### ISSUE TITLE
Criar navegação principal

### ISSUE THREAD

**Issue by rodrigomuniz** [vtex/design.vtex.com#16]
Na fase inicial, bernardo e eu pensamos num botão flutuante no canto inferior direito que abriria as seções
- Process (/)
- People (/team.html)
- Results (/results.html)

Mas não pensamos na solução desktop.

**Comment by dfosco** [comment]
Quarta-feira até o final do dia subo uma branch, fechamos essa semana. Tenho uma ideia de como pode ser já.

**Comment by bernardolemgruber** [comment]
KD

**Comment by dfosco** [comment]
Done by @zehfernandes
