### ISSUE TITLE
Pretty URLs

### ISSUE THREAD

**Issue by dfosco** [vtex/design.vtex.com#26]
`design.vtex.com/smart-checkout.html` >>> `design.vtex.com/smart-checkout`

**Comment by dfosco** [comment]
@augustocb @zehfernandes sabem como fazer?

@leandrooriente talvez?

**Comment by augustocb** [comment]
dá pra fazer isso e mais umas coisinhas: https://gist.github.com/ScottPhillips/1721489

**Comment by leandrooriente** [comment]
Coloquem /smart-checkout/index.html no lugar de smart-checkout.html

Beijos de luz

**Comment by augustocb** [comment]
é a solução mais simples, mas acho meio feia. além de deixar a estrutura meio cagada pra trabalhar.

**Comment by leandrooriente** [comment]
A recomendação do Github é usar jekyll que já resolve essa estrutura de
pastas.

Fora disso é meio limitado mesmo. Ou coloca um server na frente só pra
resolver isso ou sai do gh-pages

On Tuesday, 12 July 2016, Augusto <notifications@github.com> wrote:

> é a solução mais simples, mas acho meio feia. além de deixar a estrutura
> meio cagada pra trabalhar.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vtex/design.vtex.com/issues/26#issuecomment-232087992>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABstD3zqMyKDKOpkd8n79K2AQviMeNpsks5qU7T8gaJpZM4JKfGh>
> .
>


-- 
Att,
Leandro Oriente - Desenvolvedor Front End
lab.vtex.com
+55 21 994617213
